# -*- coding: utf-8 -*-
"""08 - Carregando dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUFMCzMPpPQXz0q9qDL6_GeXol6FxQV6
"""

#manipulação de dados
import pandas as pd

# carregando dados de diferentes tipos de arquivos

df = pd.read_csv('base_vendas.csv')
df.head()

# read_csv por padrão usa ',' como separador
# outros separadores ';' - '\t'

df = pd.read_csv('base_vendas_ponto_virgula.csv', sep=';')
df.head()

df = pd.read_csv('base_vendas_tab.tsv', sep='\t')
df.head()

df = pd.read_hdf('base_vendas.h5')
df.head()

df = pd.read_json('base_vendas.json')
df.head()

df = pd.read_xml('base_vendas.xml')
df.head()

# manipulação de dados no excel

df = pd.read_excel('Vendas.xlsx', sheet_name='base_vendas')
df.head()

listas = pd.read_html('base_vendas.html')
df = listas[0]
df.head()

# importando tabela de site (Wikipedia)

lista = pd.read_html('Predefinição_Lista de PSP Models – Wikipédia, a enciclopédia livre.html')
df = lista[0]
df.head()

# importando banco de dados

import sqlite3

conn = sqlite3.connect('vendas.db')

df = pd.read_sql_query('select * from pedidos', conn)
df.head()

# exportando para arquivo excel

df.to_excel('base_vendas.xlsx')