# -*- coding: utf-8 -*-
"""09 - Análise exploratória.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0BhKDdlXCFL-kjeqJPW3asvAcF9sksH

#CRISP-DM

1. Compreensão do Negócio: Definir os objetivos do projeto e os requisitos do
ponto de vista do negócio.

2. Compreensão dos Dados: Coletar e explorar os dados para entender sua estrutura e qualidade, identificando quais variáveis são relevantes.

3. Preparação dos Dados: Selecionar, limpar e transformar os dados brutos em um formato adequado para a modelagem. Esta fase pode consumir até 60% do tempo do projeto.

4. Modelagem: Selecionar e aplicar as técnicas de modelagem apropriadas para analisar os dados e encontrar padrões.

5. Avaliação: Avaliar os modelos construídos para verificar se eles atendem aos objetivos definidos na fase de compreensão do negócio e se são eficazes.

6. Implementação: Implantar o modelo final em produção, seja através de relatórios, dashboards ou outras aplicações, para que ele possa gerar valor de forma contínua.
"""

import pandas as pd

df_vendas = pd.read_csv('base_vendas.csv')

# .head(x) - padrão mostra as primeiras x linhas
df_vendas.head(3)

# .tail(x) - padrão mostra as últimas x linhas
df_vendas.tail(3)

# mostra em dataFrames pequenos todas as linhas
# Dataframes grandes mostra as 5 primeiras e as 5 últimas
display(df_vendas)

# visão geral da base de dados (é possível observar que algumas colunas estão com o tipo incorreto e existem linhas nulas na comissão)
df_vendas.info()

# (linhas, colunas)
df_vendas.shape

# utilidades para dados numéricos, nem sempre tudo pode ser aproveitado
df_vendas.describe().round(2)

# incluindo dados não numéricos (strings, datetime)
df_vendas.describe(include='object')

# quantidade de linhas duplicadas
df_vendas.duplicated().sum()

# quantidade de linhas com informações nulas de cada coluna
# df_vendas.isnull().sum() mesma coisa
df_vendas.isna().sum()

# instâncias distintas das colunas
df_vendas.nunique()

# instâncias distintas da coluna especificada
df_vendas.nome_loja.unique()

# outra forma
df_vendas['Nome Funcionario'].unique()

# nomes de todas as colunas
df_vendas.columns

"""##Exercício"""

# base airbnb
df_bnb = pd.read_csv('listings.csv')
display(df_bnb)

df_bnb.info()

df_bnb.describe(include='object')

df_bnb.describe().round(2)

df_bnb.isna().sum()

df_bnb.nunique()

df_bnb.duplicated().sum()

df_bnb.host_name.unique()

df_bnb['neighbourhood'].unique()

df_bnb.columns

# base titanic
df_titanic = pd.read_csv('Titanic Dataset.csv', sep=';')
display(df_titanic)

df_titanic.describe()

df_titanic['Sobreviveu'].sum()

df_titanic.nunique()